### ISSUE TITLE
Cannot run Arch linux

### ISSUE THREAD

**Issue by Ygarr** [hexoshi/hexoshi#8]
```
python3 -m pip install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by Ygarr** [comment]
Then got:
```
./hexoshi.py -mq                               
<frozen importlib._bootstrap>:241: RuntimeWarning: Your system is avx2 capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
pygame 2.6.0.dev1 (SDL 2.28.1, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/../hexoshi/./hexoshi.py", line 37, in <module>
    import xsge_gui
ModuleNotFoundError: No module named 'xsge_gui'

```

Pygame installed:
aur/python-pygame-git 1.9.4.r256.g9e24832d-1 (+7 0.00) (Installed: 2.5.0.r14.g16b44b5b3-1)

**Comment by onpon4** [comment]
I'm sorry, this issue is invalid. It's not a problem with Hexoshi, it's just an issue with your specific Python setup and how you have to do package management, as the message you got indicates. My first guess would be that maybe you need to pass the --user command to pip, or you might want to try using the pipx command, as the output you got suggested. I can't really provide support right now, thô, because Hexoshi is unfortunately in a sort of frankenstein and likely at least partially broken state right now (which is why we don't have any official releases at the moment).

If you're trying to run one of the old demo releases, I would note that some of those releases' dependencies are unmaintained and no longer on pip, and they likely require an older Pygame version as well. Taking a quick look, this is the last release of the missing package:

http://download.savannah.nongnu.org/releases/xsge/xsge_tmx/1.1/xsge_tmx-1.1.2.tar.gz

Everything else should be obtainable from pip or from here:

https://github.com/python-sge

🦇
